lib/alarmist/handler.ex

Normally the alarm handler should be swapped on init. That's what's
currently done. However when debugging, it's convenient to change out
the handler or recover it after a crash. That turns out to be a pain
since `:alarm_handler` is only the initial handler on SASL startup. This
makes the init code handle the other ways it could be added in a
reasonable way.

Make alarm handler more flexible when debugging

---

README.md
lib/alarmist.ex
lib/alarmist/application.ex
lib/alarmist/event.ex
mix.exs
mix.lock
test/alarmist_test.exs

BACKWARDS INCOMPATIBLE CHANGE
This fixes the TODO to create a custom event type for Alarmist. The main
advantage here is to make Alarmist easier to use since the PropertyTable
internals aren't exposed.  The second reason is that the PropertyTable
schema is changing and if we're going to break the API, we might as well
just do it once.

Switch from PropertyTable events to a built-in one

---

lib/alarmist.ex
lib/alarmist/engine.ex
lib/alarmist/event.ex
lib/alarmist/handler.ex
lib/alarmist/ops.ex
test/alarmist/engine_test.exs
test/alarmist_test.exs

This combines alarm state and description data into one PropertyTable
property. This removes a race when getting state and descriptions where
code would get both and one would change partway. With only one row per
alarm, there's no issue.
This also allows code to be simplified throughout. The action list
optimization was simplified to be easier to verify correctness. The
optimization is still tricky, so more tests were added.

Simplify PropertyTable use

---

lib/alarmist.ex
lib/alarmist/engine.ex
lib/alarmist/event.ex

This makes some of the specs easier to read since you don't need to
figure out the intention behind the any.

Provide a type for alarm descriptions

---

lib/alarmist.ex
test/alarmist_test.exs

Previously the only way you could fetch the alarm description was by calling `PropertyTable` directly.
This changes the return value of `Alarmist.current_alarms/0` to be a list of tuples, containing the alarm ID and the description.

Return alarm description with ID when calling `Alarmist.current_alarms/0`

---

README.md
lib/alarmist.ex
lib/alarmist/event.ex
test/alarmist_test.exs

This replaces the use of `nil`'s to indicate unknown. The goal is to
give a intentional unknown result to avoid any guesses if the `nil` was
a coding error. This only affects the `previous_state` right now.

Introduce :unknown state when the alarm status isn't know

---

lib/alarmist/engine.ex
test/alarmist_test.exs

This fixes an issue where a timeout from an expired timer would
incorrectly clear out a non-expired timer. This fixes #25.
This includes the simple test sequence from the issue that replicated
the problem.

Fix incorrect clearing of expired timer

---

lib/alarmist/definition.ex
test/alarmist/defalarm_test.exs

Alarms created using `defalarm/1` now have a `__get_alarm_def/0` function
that returns a string representation of the AST used to create the
alarm.

Add function to get AST from `defalarm`

---

lib/alarmist.ex

Adds utility functions `Alarmist.subscribe_all/0` and
`Alarmist.unsubscribe_all/0` for subscribing to all alarm events.

Subscribe to all alarm events

---

lib/alarmist.ex
lib/alarmist/engine.ex

This doesn't include unit tests since I cherry-picked it out of another
branch with a lot of unit test updates and didn't want to deal with
the conflicts.

Fix remove_synthetic_alarm to remove the right alarm

---

lib/alarmist.ex
lib/alarmist/engine.ex
test/alarmist_test.exs

This can happen when recovering from a crash or restarting an
application that registers a synthetic alarm. The existing code to check
for duplicate registrations actually didn't work and when it was fixed,
it raised which wasn't helpful.

Gracefully handle redundant alarm registration

---

README.md
examples/wifi_demo/README.md
examples/wifi_demo/lib/wifi_demo/application.ex
examples/wifi_demo/lib/wifi_demo/wifi_unstable.ex
lib/alarmist.ex
lib/alarmist/alarm.ex
lib/alarmist/compiler.ex
lib/alarmist/engine.ex
lib/alarmist/handler.ex
lib/alarmist/ops.ex
test/alarmist/alarm_if_test.exs
test/alarmist/defalarm_test.exs
test/alarmist_test.exs

See https://github.com/smartrent/alarmist/issues/39 for the reasoning behind most of the renames. The introduction of the alarm types concept is coming in the PR with parameterized alarms.
This PR doesn't have any logic changes.

Many breaking renames 

---

.circleci/config.yml
README.md
lib/alarmist.ex
lib/alarmist/alarm.ex
lib/alarmist/engine.ex
lib/alarmist/event.ex
lib/alarmist/handler.ex
mix.exs
test/alarmist/engine_test.exs
test/alarmist_test.exs
test/integration/boolean_test.exs
test/support/alarm_utililities.ex
test/support/not_not_alarm.ex
test/support/severity_alarms.ex

This makes it possible to filter and sort through active alarms and also
to more easily ignore all of the temporary ones. Alarms severities
are the same values as Logger levels. The default is `:warning`.
This drops support for Elixir 1.15 to avoid handling the differences
with the pre-1.16 Logger.
This addresses #22 by making internal alarm IDs have `:debug` severity
and then making the default when getting alarms be to only include
`:info` and higher.

Add alarm severities

---

README.md
lib/alarmist.ex
lib/alarmist/alarm.ex
lib/alarmist/compiler.ex
lib/alarmist/engine.ex
lib/alarmist/event.ex
lib/alarmist/handler.ex
lib/alarmist/matcher.ex
test/alarmist/alarm_if_test.exs
test/alarmist/compiler_test.exs
test/alarmist/matcher_test.exs
test/alarmist_test.exs
test/integration/parameterized_test.exs
test/support/compound_tuple1_alarm.ex
test/support/identity_tuple_alarms.ex

This adds the concept of alarm_type to differentiate references to
alarms that aren't fully specified. Currently only alarm_ids that are
tagged tuples like `{alarm_name, arg1, arg2 ...}` are supported.
A motivating use case is for separating network alarms based on network
interface. For example, you can now have a `NetworkBroken` alarm that
gets set and cleared as `{NetworkBroken, "eth0"}`.

Add parameterized alarm support

---

README.md
lib/alarmist.ex
lib/alarmist/handler.ex
test/alarmist_test.exs

It turns out that managed alarms that were to be added via the app
environment never were actually added. This was an undocumented feature.
In addition to the fix, this adds unit tests and a short paragraph to
the readme.

Fix issue that skips app environment alarms

---

lib/alarmist/application.ex
lib/alarmist/handler.ex
test/alarmist_test.exs

This PR addresses a problem that probably affects unit tests the most
where there's a race between application start and a call to the
handler. Amazingly, this was going unnoticed in tests due to the return
value from `:gen_event.call` not being checked. Most functions only
return `:ok` based on spec, so this wasn't expected. When this
manifested in an error, it was quite a bit later when some state wasn't
available.
There are two main pieces to this PR. One is to add retries to the
`:gen_event.call` calls so that users don't have to worry about the
race. The calls still obey the 5 second timeout with the retries. In the
future, it might be desirable to expose the timeout to users like is
frequently done with `GenServer.call`.
The second part of the PR is to clean up Application start and …

Fix startup race due to async handler initialization

---

lib/alarmist.ex
lib/alarmist/handler.ex
test/alarmist_test.exs

The retry mechanism can potentially end in a negative timeout number in situations where the handler is either missing or failing to start. This would result in a more confusing error rather than the intended RuntimeError made for these cases.
This fixes that to avoid creating negative timeouts during the retry loop. It may give up some milliseconds, but ensures the appropriate helpful error happens
```
** (EXIT from #PID<0.351.0>) an exception was raised:
** (FunctionClauseError) no function clause matching in :gen.call/4
The following arguments were given to :gen.call/4:
:alarm_handler
#PID<0.352.0>
{:call, Alarmist.Handler, {:add_managed_alarm, MyAlarm, %{options: %{parameters: [], style: :atom}, rules: [{Alarmist.Ops, :debounce, [MyAlarm, MyAlarm.Requesting, 3600000]}], temporaries: …
```

Prevent failing gen_event calls when adding managed alarms

---

lib/alarmist.ex
lib/alarmist/event.ex
test/alarmist_test.exs

This makes it possible to get the state of one alarm quickly. Previously
the only way was to get all alarms and see if the one of interest was in
the the list.

Add Alarmist.alarm_state/1 to get the state of 1 alarm

---

lib/alarmist/event.ex
lib/alarmist/info.ex
test/alarmist/event_test.exs
test/alarmist/info_test.exs

Alarmist timestamps are always in native monotonic time units but that's
not ideal for users looking at or logging the alarms. This adds a simple
conversion utility.
This also switches from NaiveDateTime to DateTime so that the time zone
is included.

Add timestamp helper function; use DateTime for conversion

---

README.md
lib/alarmist/alarm.ex
lib/alarmist/compiler.ex
lib/alarmist/engine.ex
lib/alarmist/ops.ex
lib/alarmist/window.ex
test/alarmist/alarm_if_test.exs
test/alarmist/window_test.exs
test/integration/intensity_test.exs
test/integration/on_time_test.exs
test/integration/sustain_window_test.exs
test/support/on_time_alarm.ex
test/support/sustain_window_alarm.ex

This makes it more clear than combining debounce/hold that the intent is
to require an alarm to be on for at least a duration straight within a
window.
This stacks on the windowed PR refactoring.

Add sustain_window function

---

lib/alarmist/compiler.ex
test/alarmist/alarm_if_test.exs

This also adds more tests since this was subtle.

Reduce number of intermediates with tuple alarm ids

---

test/alarmist/alarm_if_test.exs

This worked, but an accident made me unsure and that path didn't look
well tested. If it wasn't covered before with other tests, now it's
covered.

Add unit test for function with parameterized alarm ids
